============================= test session starts ==============================
platform darwin -- Python 3.11.5, pytest-7.4.2, pluggy-1.3.0
rootdir: /Users/pg/Coding/_bucket/test-fixer
collected 3 items

examples/tests/test_sum.py .F.                                           [100%]

=================================== FAILURES ===================================
__________________ test_sum_printer[args1-1 + 2 + 3 + 4 = 11] __________________

args = [1, 2, 3, 4], expected = '1 + 2 + 3 + 4 = 11'

    @pytest.mark.parametrize(
        "args, expected",
        [
            ([1, 2, 3], "1 + 2 + 3 = 6"),
            ([1, 2, 3, 4], "1 + 2 + 3 + 4 = 11"),
            ([1], "1 = 1"),
        ],
    )
    def test_sum_printer(args, expected):
>       assert sum_printer(*args) == expected
E       AssertionError: assert '1 + 2 + 3 + 4 = 10' == '1 + 2 + 3 + 4 = 11'
E         - 1 + 2 + 3 + 4 = 11
E         ?                  ^
E         + 1 + 2 + 3 + 4 = 10
E         ?                  ^

examples/tests/test_sum.py:15: AssertionError
=========================== short test summary info ============================
FAILED examples/tests/test_sum.py::test_sum_printer[args1-1 + 2 + 3 + 4 = 11]
========================= 1 failed, 2 passed in 0.02s ==========================
